services:

  db:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb_inception
    init: true
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - wp_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "sh", "-c", "mariadb-admin ping -h localhost -u $MARIADB_USER -p$(cat /run/secrets/db_password)"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - inception
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  wp:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress_inception
    init: true
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user_password
    volumes:
      - wp_websites:/var/www/html
    networks:
      - inception
    healthcheck:
      test: ["CMD", "sh", "-c", "ss -lnt | grep ':9000 '"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx_inception
    init: true
    secrets:
      - ssl_cert
      - ssl_key
    volumes:
      - wp_websites:/var/www/html:ro
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      wp:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  inception:

volumes:
  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/suwi/data/mysql
  wp_websites:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/suwi/data/html

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ssl_cert:
    file: ../secrets/ssl_cert.crt
  ssl_key:
    file: ../secrets/ssl_key.key
