services:

  db:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb_inception
    init: true
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_name
      - db_user
      - db_password
    volumes:
      - wp_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "sh", "-c", "mariadb-admin ping -h localhost -u $(cat /run/secrets/db_user) -p$(cat /run/secrets/db_password)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - inception
    restart: unless-stopped

  wp:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress_inception
    init: true
    env_file:
      - .env
    secrets:
      - db_name
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user_password
    volumes:
      - wp_websites:/var/www/html
    networks:
      - inception
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx_inception
    init: true
    volumes:
      - wp_websites:/var/www/html:ro
    ports:
      - 4443:443
    networks:
      - inception
    depends_on:
      - wp
    restart: unless-stopped

networks:
  inception:

volumes:
  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/suwi/data/mysql
  wp_websites:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/suwi/data/html

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_name:
    file: ../secrets/db_name.txt
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
