services:

  db:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb_inception
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MARIADB_USER}", "-p${MARIADB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - inception
    restart: unless-stopped

  wp:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress_inception
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx_inception
    volumes:
      - wordpress_data:/var/www/html:ro
    ports:
      - 4443:443
    networks:
      - inception
    depends_on:
      - wp
    restart: unless-stopped

networks:
  inception:

volumes:
  mariadb_data:
  wordpress_data:


